CREATE TABLE Cliente
(
	CL#			VARCHAR2(5) PRIMARY KEY,
	Nombre		VARCHAR2(50),
	DNI			VARCHAR2(9)
);

	CREATE TABLE Tipo
(
	TI#			VARCHAR2(5) PRIMARY KEY,
	Nombre		VARCHAR2(50),
	DNI			VARCHAR2(9)
);
	
	CREATE TABLE Producto
(
	PR#			VARCHAR2(3) PRIMARY KEY,
	Nombre		VARCHAR2(50),
	TI#			VARCHAR2(5) REFERENCES Tipo(TI#)
);

	CREATE TABLE Compra
(
	CL#			VARCHAR2(5) REFERENCES Cliente(CL#),
	PR#			VARCHAR2(5) REFERENCES Producto(PR#)
);

	CREATE TABLE Yogur
(
	YO#			VARCHAR2(5) PRIMARY KEY,
	Sabor		VARCHAR2(50),
	PR#			VARCHAR2(5) REFERENCES Producto(PR#)
);

	CREATE TABLE Leche
(
	LE#			VARCHAR2(5) PRIMARY KEY,
	Nata		VARCHAR2(20),
	Capacidad	VARCHAR2(3),
	PR#			VARCHAR2(5), REFERENCES Producto(PR#)
);

	CREATE TABLE Mantequilla
(
	MA#			VARCHAR2(5) PRIMARY KEY,
	Acidez		VARCHAR2(20),
	Origen		VARCHAR2(20),
	Peso		VARCHAR2(6),
	PR#			VARCHAR2(5) REFERENCES Producto(PR#)
);