CREATE TABLE Categoria (
CA# VARCHAR2(4),
NombreCategoria VARCHAR2(20),
CONSTRAINT PK_Categoria_CA# PRIMARY KEY (CA#)
);
CREATE TABLE Estilo (
ES# VARCHAR2(4),
NombreEstilo VARCHAR2(20),
CONSTRAINT PK_Estilo_ES# PRIMARY KEY (ES#)
);
CREATE TABLE Editorial (
ED# VARCHAR2(4),
NombreEditorial VARCHAR2(35),
DireccionEditorial VARCHAR2(20),
CIF VARCHAR2(10),
AnioCreacion VARCHAR2(20),
CONSTRAINT PK_Editorial_ED# PRIMARY KEY (ED#)
);
CREATE TABLE Autor (
AU# VARCHAR2(4),
NombreAutor VARCHAR2(20),
CONSTRAINT PK_Autor_AU# PRIMARY KEY (AU#)
);
CREATE TABLE Libro (
LI# VARCHAR2(4),
NombreLibro VARCHAR2(35),
Fecha DATE,
ES# VARCHAR2(4),
CA# VARCHAR2(4),
AU# VARCHAR2(4),
ED# VARCHAR2(4),
CONSTRAINT PK_Libro_LI# PRIMARY KEY (LI#),
CONSTRAINT FK_Libro_ED# FOREIGN KEY (ED#) REFERENCES Editorial(ED#),
CONSTRAINT FK_Libro_CA# FOREIGN KEY (CA#) REFERENCES Categoria(CA#),
CONSTRAINT FK_Libro_AU# FOREIGN KEY (AU#) REFERENCES Autor(AU#),
CONSTRAINT FK_Libro_ES# FOREIGN KEY (ES#) REFERENCES Estilo(ES#)
);
CREATE TABLE Escribe (
AU# VARCHAR2(4),
LI# VARCHAR2(4),
CONSTRAINT FK_Escribe_AU# FOREIGN KEY (AU#) REFERENCES Autor(AU#),
CONSTRAINT FK_Escribe_LI# FOREIGN KEY (LI#) REFERENCES Libro(li#)
);
CREATE TABLE Usuario (
US# VARCHAR2(4),
NombreUsuario VARCHAR2(10),
ApellidosUsuario VARCHAR2(20),
DireccionUsuario VARCHAR2(20),
CONSTRAINT PK_Usuario_US# PRIMARY KEY (US#)
);
CREATE TABLE Empleado (
EM# VARCHAR2(4),
NombreEmpleado VARCHAR2(10),
ApellidosEmpleado VARCHAR2(20),
Turno VARCHAR2(12),
CONSTRAINT PK_Empleado_EM# PRIMARY KEY (EM#)
);
CREATE TABLE Resguardo (
RE# VARCHAR2(4),
FechaRecogida DATE,
FechaEntrega DATE,
CONSTRAINT PK_Resguardo_RE# PRIMARY KEY (RE#)
);
CREATE TABLE Tiene (
RE# VARCHAR2(4),
LI# VARCHAR2(4),
CONSTRAINT FK_Tiene_RE# FOREIGN KEY (RE#) REFERENCES Resguardo(RE#),
CONSTRAINT FK_Tiene_LI# FOREIGN KEY (LI#) REFERENCES Libro(LI#)
);
CREATE TABLE Prestamo (
US# VARCHAR2(4),
EM# VARCHAR2(4),
RE# VARCHAR2(4),
CONSTRAINT FK_Prestamo_US# FOREIGN KEY (US#) REFERENCES Usuario(US#),
CONSTRAINT FK_Prestamo_EM# FOREIGN KEY (EM#) REFERENCES Empleado(EM#),
CONSTRAINT FK_Prestamo_RE# FOREIGN KEY (RE#) REFERENCES Resguardo(RE#)
);
COMMIT;

