CREATE TABLE Editorial
(
ED# VARCHAR2(4),
Nombre VARCHAR2(30),
Direccion VARCHAR2(30),
CIF VARCHAR2(12),
Actividad VARCHAR2(30),
AnioCrea NUMBER(3),
CONSTRAINT PK_Editorial_ED# PRIMARY KEY (ED#)
);
CREATE TABLE Publicacion
(
PU# VARCHAR2(4),
Importe NUMBER(7,2),
Fecha DATE,
ED# VARCHAR2(4),
CONSTRAINT PK_Publicacion_PU# PRIMARY KEY (PU#),
Constraint FK_Publicacion_ED# FOREIGN KEY (ED#) REFERENCES Editorial(ED#)
);
CREATE TABLE Articulo
(
AR# VARCHAR2(4),
Descripcion VARCHAR2(30),
PU# VARCHAR2(4),
CONSTRAINT PK_Articulo_AR# PRIMARY KEY (AR#),
CONSTRAINT FK_Articulo_PU# FOREIGN KEY (PU#) REFERENCES Publicacion(PU#)
);
CREATE TABLE Libro
(
LI# VARCHAR2(4),
Titulo VARCHAR2(30),
NPaginas NUMBER(4),
PU# VARCHAR(4),
CONSTRAINT PK_Libro_LI# PRIMARY KEY (LI#),
CONSTRAINT FK_Libro_PU# FOREIGN KEY (PU#) REFERENCES Publicacion(PU#),
CONSTRAINT CK_Libro_NPaginas CHECK (NPaginas < 1200)
);
CREATE TABLE Autor
(
AU# VARCHAR2(4),
Nombre VARCHAR2(30),
CONSTRAINT PK_Autor_AU# PRIMARY KEY (AU#)
);
CREATE TABLE Escribe
(
AU# VARCHAR2(4),
PU# VARCHAR2(4),
CONSTRAINT FK_Escribe_AU# FOREIGN KEY (AU#) REFERENCES Autor(AU#),
CONSTRAINT FK_Escribe_PU# FOREIGN KEY (PU#) REFERENCES Publicacion(PU#)
);
CREATE TABLE Factura
(
FA# VARCHAR2(4),
Identificador VARCHAR2(30),
CONSTRAINT PK_Factura_FA# PRIMARY KEY (FA#)
);
CREATE TABLE Tiene
(
FA# VARCHAR2(4),
PU# VARCHAR2(4),
CONSTRAINT FK_Tiene_FA# FOREIGN KEY (FA#) REFERENCES Factura(FA#),
CONSTRAINT FK_Tiene_PU# FOREIGN KEY (PU#) REFERENCES Publicacion(PU#)
);
CREATE TABLE Cliente
(
CL# VARCHAR2(4),
Nombre VARCHAR2(30),
Direccion VARCHAR2(30),
DNI VARCHAR2(9),
Edad VARCHAR2(2),
Telefono NUMBER(9),
CONSTRAINT PK_Cliente_CL# PRIMARY KEY (CL#)
);
CREATE TABLE Empleado
(
EM# VARCHAR2(4),
Nombre VARCHAR2(30),
Edad VARCHAR2(2),
Domicilio VARCHAR2(30),
AnyosExperiencia VARCHAR2(2),
CONSTRAINT PK_Empleado_EM# PRIMARY KEY (EM#)
);
CREATE TABLE Turno
(
TU# VARCHAR2(4),
Nombre VARCHAR2(30),
CONSTRAINT PK_Turno_TU# PRIMARY KEY (TU#),
CONSTRAINT CK_Turno_TU# CHECK (TU# = 'mana' OR 
TU# = 'tard' OR TU# = 'fine' OR TU# = 'cont')
);
CREATE TABLE Trabaja
(
EM# VARCHAR2(4),
TU# VARCHAR2(4),
CONSTRAINT FK_Trabaja_EM# FOREIGN KEY (EM#) REFERENCES Empleado(EM#),
CONSTRAINT FK_Trabaja_TU# FOREIGN KEY (TU#) REFERENCES Turno(TU#)
);
CREATE TABLE Compra
(
FormaPago VARCHAR2(30),
Fecha DATE DEFAULT SYSDATE,
Precio NUMBER(7,2),
CL# VARCHAR2(4),
EM# VARCHAR2(4),
FA# VARCHAR2(4),
CONSTRAINT FK_Compra_CL# FOREIGN KEY (CL#) REFERENCES Cliente(CL#),
CONSTRAINT FK_Compra_EM# FOREIGN KEY (EM#) REFERENCES Empleado(EM#),
CONSTRAINT FK_Compra_FA# FOREIGN KEY (FA#) REFERENCES Factura(FA#),
CONSTRAINT CK_Compra_FormaPago CHECK (FormaPago = 'Tarjeta' 
OR FormaPago = 'Cheque' OR FormaPago = 'Efectivo')
);
COMMIT;
